### ISSUE TITLE
Opens and closes almost immediately

### ISSUE THREAD

**Issue by InputSoldatcc** [thisisignitedoreo/sppite#1]
Self explanatory, the windows terminal pops up, a big wall of text follows, then it closes. Haven't looked into the source code or earlier releases yet though.

**Comment by thisisignitedoreo** [comment]
it most certainly crashes, run it in cmd, do screenshot and send it here.

**Comment by InputSoldatcc** [comment]
Hmm. 
![image](https://github.com/thisisignitedoreo/sppite/assets/140076004/d7920ca3-5fae-4902-8764-02e4cc8abd4e)

I am going to try installing python, instead of _just_ the DLL first, thats probably what I did wrong.

**Comment by InputSoldatcc** [comment]
![image](https://github.com/thisisignitedoreo/sppite/assets/140076004/0c60da3a-ffa1-4675-be96-ccb77ab32d39)
Probably has something to do with this aswell.

**Comment by thisisignitedoreo** [comment]
> ![image](https://private-user-images.githubusercontent.com/140076004/347081181-0c60da3a-ffa1-4675-be96-ccb77ab32d39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NTMyMDQsIm5iZiI6MTcyMDU1MjkwNCwicGF0aCI6Ii8xNDAwNzYwMDQvMzQ3MDgxMTgxLTBjNjBkYTNhLWZmYTEtNDY3NS1iZTk2LWNjYjc3YWIzMmQzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQxOTIxNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNjA3OTU4MDA0YzE4ZjZmZGU3YWUzZTlhYTE3ODFkYTFjMzk3NzVmMzU0NjRlMzU1YzEwMWNlZWIwNTA2ZTQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.45TsaUFQf13Zgi7dF4Z-Xqi3tc-4-M3khGJmxod22D0) Probably has something to do with this aswell.

also, it points to python in **my** home directory. maybe nuitka hardcodes python path instread of shipping it with executable?

**Comment by InputSoldatcc** [comment]
No problem. Im just as confused as you are though xD

**Comment by thisisignitedoreo** [comment]
misread documentation, it does just point to my python installation.

i compiled standalone release, try it

**Comment by thisisignitedoreo** [comment]
ill assume you tried it and it fixed your problem, and closing the issue. feel free to reopen it otherwise.

**Comment by InputSoldatcc** [comment]
Was just trying it lol, the initial error is fixed; however...
![image](https://github.com/thisisignitedoreo/sppite/assets/140076004/02eb21f8-e645-400f-81dd-93a613821555)

_This is opened in cmd_

**Comment by thisisignitedoreo** [comment]
try latest release, it **should** work
frickin python...

**Comment by InputSoldatcc** [comment]
Now it works perfectly without any issues. However I did have to turn off the anti virus for when I ran it, but thats not an issue.

**Comment by thisisignitedoreo** [comment]
av thing is something with python packing in general, i.e. pyinstaller is detected on most av's
thank you for reporting!
